[package]
name = "rust-wasm-app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rust-wasm-app"
path = "src/main.rs"

[dependencies]
wasm-bindgen = "0.2"
yew = { version = "0.21", features = ["csr"] }

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]
